### ISSUE TITLE
Update WorldWind Java documentation

### ISSUE THREAD

**Issue by eirizarry** [NASAWorldWind/WorldWindJava#121]
Update the overall documentation in the WorldWind Java repository.

Add several new files which outline the project's contribution guidelines. It is designed for both the WorldWind team and any users who wish to open an issue or pull request in the WorldWind Java repository.

Make "WorldWind" the name standard (as opposed to "World Wind"). This will ensure that the project name is consistent with the website and all other project repositories.

Implementation stories:

- [x] Add CONTRIBUTING.md [(#122)](https://github.com/NASAWorldWind/WorldWindJava/issues/122)
- [x] Add ISSUE_TEMPLATE.md [(#123)](https://github.com/NASAWorldWind/WorldWindJava/issues/123)
- [x] Add PR_TEMPLATE.md [#124)](https://github.com/NASAWorldWind/WorldWindJava/issues/124)
- [x] Make "WorldWind" the name standard [(#125)](https://github.com/NASAWorldWind/WorldWindJava/issues/125)
